source 'https://rubygems.org'

ruby "2.2.3"
gem 'rails', '4.2.4'
gem 'pg'
gem 'doorkeeper', '~> 3.1.0'
gem 'formtastic', '~> 2.2.1'
gem 'validates_email_format_of', '~> 1.5.3'
gem 'cancan', '~> 1.6.8'
gem 'rails-i18n', '~> 0.6.5'
gem 'highline', '~> 1.6.14'
gem 'airbrake', '~> 3.1.6'
gem 'memcachier', '~> 0.0.2'
gem 'dalli', '~> 2.3.0'
gem 'turbolinks', '~> 0.5.1'
gem 'thin', '~> 1.4.1'
gem 'feature', '~> 0.5.0'
gem 'delayed_job_active_record', '~> 4.1.0'
gem 'carrierwave', '~> 0.9.0'
gem 'rmagick', '~> 2.13.4'
gem 'fog', '~> 1.38.0'
gem 'draper', '~> 1.2.1'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'jquery-rails', '~> 4.1.1'
gem 'pry-rails', '~> 0.2.1'
gem 'newrelic_rpm', '~> 3.15.1.316'
gem "sudo_mode", "~> 1.0.0"
gem 'activeresource', '~> 4.0.0'
gem 'protected_attributes'

group :assets do
  gem 'compass-rails', '~> 2.0.4'
  gem 'sass-rails',   '~> 5.0.4'
  gem 'coffee-rails', '~> 4.1.1'
  gem 'susy', '~> 1.0'
  gem 'compass-normalize', '~> 1.1.2'
 # gem 'formalize-rails', '~> 0.1.3'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'zeus', '~> 0.13.3'
#  gem 'heroku', '~> 2.28.12'
  gem 'figaro', '~> 1.0.0'
  gem 'rspec-rails', '~> 3.4.2'
  gem 'rspec-http', '~> 0.11.0'
  gem 'guard-spork', '~> 2.1.0'
  gem 'guard-livereload', '~> 2.5.2'
  gem 'guard-rspec', '~> 4.6.5'
  gem 'growl', '~> 1.0.3'
  gem 'factory_girl_rails', '~> 4.2.0'
  gem 'email_spec', '~> 2.0.0'
  gem 'timecop', '~> 0.6.1'
end

group :development do
  gem 'letter_opener', '~> 1.4.1'
  gem 'letter_opener_web', '~> 1.3.0'
  gem 'rails-erd'
  gem 'railroady'
  gem 'byebug'
end

group :production do 
  gem 'rails_12factor'
end
