source 'https://rubygems.org'

ruby "2.2.3"
gem 'rails', '4.2.4'
gem 'pg'
gem 'doorkeeper', '~> 3.1.0'
  gem 'formtastic', '~> 2.2.1'
gem 'validates_email_format_of', '~> 1.5.3'
gem 'cancan', '~> 1.6.8'
gem 'rails-i18n', '~> 0.6.5'
gem 'highline', '~> 1.6.14'
gem 'airbrake', '~> 4.3.6'
gem 'memcachier', '~> 0.0.2'
gem 'dalli', '~> 2.7.6'
gem 'turbolinks', '~> 2.5.3'
gem 'thin', '~> 1.2.11'
gem 'feature', '~> 1.3.0'
gem 'delayed_job_active_record', '~> 4.1.0'
gem 'carrierwave', '~> 0.11.2'
gem 'rmagick', '~> 2.13.4'
gem 'fog', '~> 1.38.0'
gem 'has_scope'
gem 'draper', '~> 2.1.0'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'jquery-rails', '~> 4.1.1'
gem 'pry-rails', '~> 0.3.4'
gem 'newrelic_rpm', '~> 3.15.2.317'
gem 'sudo_mode', github: 'khyateh/sudo_mode'
gem 'activeresource', '~> 4.0.0'
gem 'protected_attributes'
gem 'responders'

group :assets do
  gem 'compass-rails', '~> 3.0.2'
  gem 'sass-rails',   '~> 5.0.4'
  gem 'coffee-rails', '~> 4.1.1'
  gem 'susy', '~> 2.2.12'
  gem 'compass-normalize', '~> 1.5'
  gem 'formalize-rails', github: 'khyateh/formalize-rails'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'zeus', '~> 0.15.4'
  gem 'heroku', '~> 3.43.2'
  gem 'figaro', '~> 1.0.0'
  gem 'rspec-rails', '~> 3.4.2'
  gem 'rspec-http', '~> 0.11.0'
  gem 'guard-spork', '~> 2.1.0'
  gem 'guard-livereload', '~> 2.5.2'
  gem 'guard-rspec', '~> 4.6.5'
  gem 'growl', '~> 1.0.3'
  gem 'factory_girl_rails', '~> 4.2.0'
  gem 'email_spec', '~> 2.0.0'
  gem 'timecop', '~> 0.6.1'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development do
  gem 'letter_opener', '~> 1.4.1'
  gem 'letter_opener_web', '~> 1.3.0'
  gem 'rails-erd'
  gem 'railroady'
  gem 'byebug'
end

group :production do
  gem 'rails_12factor'
  gem 'rack-cache' 
end
