require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RespondentsController do

  # This should return the minimal set of attributes required to create a valid
  # Respondent. As you add validations to Respondent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RespondentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all respondents as @respondents" do
      respondent = Respondent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:respondents).should eq([respondent])
    end
  end

  describe "GET show" do
    it "assigns the requested respondent as @respondent" do
      respondent = Respondent.create! valid_attributes
      get :show, {:id => respondent.to_param}, valid_session
      assigns(:respondent).should eq(respondent)
    end
  end

  describe "GET new" do
    it "assigns a new respondent as @respondent" do
      get :new, {}, valid_session
      assigns(:respondent).should be_a_new(Respondent)
    end
  end

  describe "GET edit" do
    it "assigns the requested respondent as @respondent" do
      respondent = Respondent.create! valid_attributes
      get :edit, {:id => respondent.to_param}, valid_session
      assigns(:respondent).should eq(respondent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Respondent" do
        expect {
          post :create, {:respondent => valid_attributes}, valid_session
        }.to change(Respondent, :count).by(1)
      end

      it "assigns a newly created respondent as @respondent" do
        post :create, {:respondent => valid_attributes}, valid_session
        assigns(:respondent).should be_a(Respondent)
        assigns(:respondent).should be_persisted
      end

      it "redirects to the created respondent" do
        post :create, {:respondent => valid_attributes}, valid_session
        response.should redirect_to(Respondent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved respondent as @respondent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Respondent.any_instance.stub(:save).and_return(false)
        post :create, {:respondent => {}}, valid_session
        assigns(:respondent).should be_a_new(Respondent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Respondent.any_instance.stub(:save).and_return(false)
        post :create, {:respondent => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested respondent" do
        respondent = Respondent.create! valid_attributes
        # Assuming there are no other respondents in the database, this
        # specifies that the Respondent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Respondent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => respondent.to_param, :respondent => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested respondent as @respondent" do
        respondent = Respondent.create! valid_attributes
        put :update, {:id => respondent.to_param, :respondent => valid_attributes}, valid_session
        assigns(:respondent).should eq(respondent)
      end

      it "redirects to the respondent" do
        respondent = Respondent.create! valid_attributes
        put :update, {:id => respondent.to_param, :respondent => valid_attributes}, valid_session
        response.should redirect_to(respondent)
      end
    end

    describe "with invalid params" do
      it "assigns the respondent as @respondent" do
        respondent = Respondent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Respondent.any_instance.stub(:save).and_return(false)
        put :update, {:id => respondent.to_param, :respondent => {}}, valid_session
        assigns(:respondent).should eq(respondent)
      end

      it "re-renders the 'edit' template" do
        respondent = Respondent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Respondent.any_instance.stub(:save).and_return(false)
        put :update, {:id => respondent.to_param, :respondent => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested respondent" do
      respondent = Respondent.create! valid_attributes
      expect {
        delete :destroy, {:id => respondent.to_param}, valid_session
      }.to change(Respondent, :count).by(-1)
    end

    it "redirects to the respondents list" do
      respondent = Respondent.create! valid_attributes
      delete :destroy, {:id => respondent.to_param}, valid_session
      response.should redirect_to(respondents_url)
    end
  end

end
